global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9102']
  - job_name: 'hsl_rt_metrics'
    static_configs:
      - targets: ["hsl-spark-streaming-metrics:9108"]