{
 "title": "HSL Real-Time Metrics",
 "tags": [
  "prometheus",
  "spark",
  "hsl"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Active Vehicles",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_active_vehicles", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Average Speed (All Vehicles)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "km/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_speed_all", "legendFormat": "Avg Speed" }
   ]
  },
  {
   "title": "On-Time Arrival Ratio (≤1/2/3 min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "pct_routes_on_time_1", "legendFormat": "≤1 min" },
    { "expr": "pct_routes_on_time_2", "legendFormat": "≤2 min" },
    { "expr": "pct_routes_on_time_3", "legendFormat": "≤3 min" }
   ]
  },
  {
   "title": "Most Delayed Route (avg delay, min)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, last_over_time(route_delay_extreme_seconds{type=\"worst\"}[2m]) ) / 60",
     "legendFormat": "{{route_id}}"
    }
   ]
  },
  {
   "title": "Most Delayed Route (minutes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "last_over_time(route_delay_extreme_seconds{type=\"worst\"}[2m]) / 60",
     "legendFormat": "{{route_id}}"
    }
   ]
  },
  {
   "title": "Most Ahead Route (avg early, min)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bottomk(1, last_over_time(route_delay_extreme_seconds{type=\"best\"}[2m]) ) / 60",
     "legendFormat": "{{route_id}}"
    }
   ]
  },
  {
   "title": "Most Ahead Route (minutes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "last_over_time(route_delay_extreme_seconds{type=\"best\"}[2m]) / 60",
     "legendFormat": "{{route_id}}"
    }
   ]
  },
  {
   "title": "Total Active Vehicles",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "total_active_vehicles", "legendFormat": "Total" }
   ]
  }
 ]
}